# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.11

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/yuoa/lecture/cs353

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/yuoa/lecture/cs353

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yuoa/lecture/cs353/CMakeFiles /home/yuoa/lecture/cs353/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yuoa/lecture/cs353/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CShark

# Build rule for target.
CShark: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CShark
.PHONY : CShark

# fast build rule for target.
CShark/fast:
	$(MAKE) -f CMakeFiles/CShark.dir/build.make CMakeFiles/CShark.dir/build
.PHONY : CShark/fast

# target to build an object file
analyze.pcap.o:
	$(MAKE) -f CMakeFiles/CShark.dir/build.make CMakeFiles/CShark.dir/analyze.pcap.o
.PHONY : analyze.pcap.o

# target to preprocess a source file
analyze.pcap.i:
	$(MAKE) -f CMakeFiles/CShark.dir/build.make CMakeFiles/CShark.dir/analyze.pcap.i
.PHONY : analyze.pcap.i

# target to generate assembly for a file
analyze.pcap.s:
	$(MAKE) -f CMakeFiles/CShark.dir/build.make CMakeFiles/CShark.dir/analyze.pcap.s
.PHONY : analyze.pcap.s

# target to build an object file
capture.pcap.o:
	$(MAKE) -f CMakeFiles/CShark.dir/build.make CMakeFiles/CShark.dir/capture.pcap.o
.PHONY : capture.pcap.o

# target to preprocess a source file
capture.pcap.i:
	$(MAKE) -f CMakeFiles/CShark.dir/build.make CMakeFiles/CShark.dir/capture.pcap.i
.PHONY : capture.pcap.i

# target to generate assembly for a file
capture.pcap.s:
	$(MAKE) -f CMakeFiles/CShark.dir/build.make CMakeFiles/CShark.dir/capture.pcap.s
.PHONY : capture.pcap.s

# target to build an object file
decap.pcap.o:
	$(MAKE) -f CMakeFiles/CShark.dir/build.make CMakeFiles/CShark.dir/decap.pcap.o
.PHONY : decap.pcap.o

# target to preprocess a source file
decap.pcap.i:
	$(MAKE) -f CMakeFiles/CShark.dir/build.make CMakeFiles/CShark.dir/decap.pcap.i
.PHONY : decap.pcap.i

# target to generate assembly for a file
decap.pcap.s:
	$(MAKE) -f CMakeFiles/CShark.dir/build.make CMakeFiles/CShark.dir/decap.pcap.s
.PHONY : decap.pcap.s

# target to build an object file
get.dev.o:
	$(MAKE) -f CMakeFiles/CShark.dir/build.make CMakeFiles/CShark.dir/get.dev.o
.PHONY : get.dev.o

# target to preprocess a source file
get.dev.i:
	$(MAKE) -f CMakeFiles/CShark.dir/build.make CMakeFiles/CShark.dir/get.dev.i
.PHONY : get.dev.i

# target to generate assembly for a file
get.dev.s:
	$(MAKE) -f CMakeFiles/CShark.dir/build.make CMakeFiles/CShark.dir/get.dev.s
.PHONY : get.dev.s

# target to build an object file
handle.pcap.o:
	$(MAKE) -f CMakeFiles/CShark.dir/build.make CMakeFiles/CShark.dir/handle.pcap.o
.PHONY : handle.pcap.o

# target to preprocess a source file
handle.pcap.i:
	$(MAKE) -f CMakeFiles/CShark.dir/build.make CMakeFiles/CShark.dir/handle.pcap.i
.PHONY : handle.pcap.i

# target to generate assembly for a file
handle.pcap.s:
	$(MAKE) -f CMakeFiles/CShark.dir/build.make CMakeFiles/CShark.dir/handle.pcap.s
.PHONY : handle.pcap.s

# target to build an object file
main.core.o:
	$(MAKE) -f CMakeFiles/CShark.dir/build.make CMakeFiles/CShark.dir/main.core.o
.PHONY : main.core.o

# target to preprocess a source file
main.core.i:
	$(MAKE) -f CMakeFiles/CShark.dir/build.make CMakeFiles/CShark.dir/main.core.i
.PHONY : main.core.i

# target to generate assembly for a file
main.core.s:
	$(MAKE) -f CMakeFiles/CShark.dir/build.make CMakeFiles/CShark.dir/main.core.s
.PHONY : main.core.s

# target to build an object file
protocol.pcap.o:
	$(MAKE) -f CMakeFiles/CShark.dir/build.make CMakeFiles/CShark.dir/protocol.pcap.o
.PHONY : protocol.pcap.o

# target to preprocess a source file
protocol.pcap.i:
	$(MAKE) -f CMakeFiles/CShark.dir/build.make CMakeFiles/CShark.dir/protocol.pcap.i
.PHONY : protocol.pcap.i

# target to generate assembly for a file
protocol.pcap.s:
	$(MAKE) -f CMakeFiles/CShark.dir/build.make CMakeFiles/CShark.dir/protocol.pcap.s
.PHONY : protocol.pcap.s

# target to build an object file
select.dev.o:
	$(MAKE) -f CMakeFiles/CShark.dir/build.make CMakeFiles/CShark.dir/select.dev.o
.PHONY : select.dev.o

# target to preprocess a source file
select.dev.i:
	$(MAKE) -f CMakeFiles/CShark.dir/build.make CMakeFiles/CShark.dir/select.dev.i
.PHONY : select.dev.i

# target to generate assembly for a file
select.dev.s:
	$(MAKE) -f CMakeFiles/CShark.dir/build.make CMakeFiles/CShark.dir/select.dev.s
.PHONY : select.dev.s

# target to build an object file
sub.core.o:
	$(MAKE) -f CMakeFiles/CShark.dir/build.make CMakeFiles/CShark.dir/sub.core.o
.PHONY : sub.core.o

# target to preprocess a source file
sub.core.i:
	$(MAKE) -f CMakeFiles/CShark.dir/build.make CMakeFiles/CShark.dir/sub.core.i
.PHONY : sub.core.i

# target to generate assembly for a file
sub.core.s:
	$(MAKE) -f CMakeFiles/CShark.dir/build.make CMakeFiles/CShark.dir/sub.core.s
.PHONY : sub.core.s

# target to build an object file
test.pcap.o:
	$(MAKE) -f CMakeFiles/CShark.dir/build.make CMakeFiles/CShark.dir/test.pcap.o
.PHONY : test.pcap.o

# target to preprocess a source file
test.pcap.i:
	$(MAKE) -f CMakeFiles/CShark.dir/build.make CMakeFiles/CShark.dir/test.pcap.i
.PHONY : test.pcap.i

# target to generate assembly for a file
test.pcap.s:
	$(MAKE) -f CMakeFiles/CShark.dir/build.make CMakeFiles/CShark.dir/test.pcap.s
.PHONY : test.pcap.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... CShark"
	@echo "... edit_cache"
	@echo "... analyze.pcap.o"
	@echo "... analyze.pcap.i"
	@echo "... analyze.pcap.s"
	@echo "... capture.pcap.o"
	@echo "... capture.pcap.i"
	@echo "... capture.pcap.s"
	@echo "... decap.pcap.o"
	@echo "... decap.pcap.i"
	@echo "... decap.pcap.s"
	@echo "... get.dev.o"
	@echo "... get.dev.i"
	@echo "... get.dev.s"
	@echo "... handle.pcap.o"
	@echo "... handle.pcap.i"
	@echo "... handle.pcap.s"
	@echo "... main.core.o"
	@echo "... main.core.i"
	@echo "... main.core.s"
	@echo "... protocol.pcap.o"
	@echo "... protocol.pcap.i"
	@echo "... protocol.pcap.s"
	@echo "... select.dev.o"
	@echo "... select.dev.i"
	@echo "... select.dev.s"
	@echo "... sub.core.o"
	@echo "... sub.core.i"
	@echo "... sub.core.s"
	@echo "... test.pcap.o"
	@echo "... test.pcap.i"
	@echo "... test.pcap.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

